Object-Cache Update
deliciousbrains/spinupwp-plugin pull request #50
Opened 2021-11-04 18:36 UTC by katelynnbarlowe

I've updated the drop-in based on the [Redis Cache version](https://raw.githubusercontent.com/rhubarbgroup/redis-cache/develop/includes/object-cache.php). I swapped out our variable in `wp_cache_init()`. The only thing I'm not sure about is the versioning/tagging - what should I update that to? 

It looks like we automatically compare versions and update the dropin in the `show_object_cache_dropin_updated_notice()` in `AdminNotices.php`.

2021-11-29 10:25 UTC, A5hleyRich commented
@katelynnbarlowe this could do with a refresh: 

https://github.com/rhubarbgroup/redis-cache/releases/tag/2.0.22

2021-12-06 11:51 UTC, A5hleyRich requested changes
@katelynnbarlowe a few comments.

2021-12-06 11:51 UTC, A5hleyRich commented on drop-ins/object-cache.php
> +    }
This should always be `true` in Spinup https://github.com/deliciousbrains/spinupwp-plugin/commit/7cc2b8c68cb3ff886431bdfe8511657f6503ac67#diff-e176a90a3c73dc81c0254b1712e3a7e65b13375641c60a4e8836af1bbe8958ad

2021-12-06 11:51 UTC, A5hleyRich commented on drop-ins/object-cache.php
> +    }
We don't need this.

2021-12-06 11:51 UTC, A5hleyRich commented on drop-ins/object-cache.php
> +    }
`WP_REDIS_PREFIX` and `WP_CACHE_KEY_SALT` needs reworking to handle all of these possibilities:

https://github.com/deliciousbrains/spinupwp-plugin/blob/develop/drop-ins/object-cache.php#L2001

2021-12-06 16:29 UTC, katelynnbarlowe commented
@A5hleyRich I _think_ I've gotten it where it needs to be. I added back the function that was there before to account for all of the different cases.

2022-02-01 19:07 UTC, katelynnbarlowe commented
@A5hleyRich Latest updates have been brought in! It wasn't too much.

2022-02-02 16:57 UTC, A5hleyRich commented
💯

2022-02-02 16:58 UTC, merged