object-cache.php drop-in copy now able to be aborted
deliciousbrains/spinupwp-plugin pull request #54
Opened 2022-02-07 14:56 UTC by polevaultweb

Resolves https://github.com/deliciousbrains/spinupwp-plugin/issues/53

2022-02-07 15:18 UTC, A5hleyRich commented on src/Plugin.php
> +		if ( defined( 'RedisCachePro\Version' ) ) {
I don't think so, as our version of object-cache.php sets a few preferred defaults on Spinup.

2022-02-07 16:14 UTC, A5hleyRich requested changes
@polevaultweb does the alignment look off to you? It's all kind of weird on the GH diff.

2022-02-07 16:14 UTC, A5hleyRich commented on src/Plugin.php
>  			@unlink( $wpcontent_dir . '/object-cache.php' );
👍

2022-02-07 16:14 UTC, A5hleyRich commented on src/Plugin.php
> +		self::update_object_cache_dropin();
`$wpcontent_dir` is no longer used.

2022-02-07 17:57 UTC, polevaultweb commented
@A5hleyRich back to you

2022-02-09 16:41 UTC, A5hleyRich commented
💯

2022-02-09 16:42 UTC, merged